import { GitHubStats } from "@/lib/types";
import { escapeXml, sanitizeHexParam } from "@/lib/sanitize";

export type ProfileCardType = "repo" | "profile" | "compact";

export type ProfileCardTheme = {
  bg: string;
  panel: string;
  text: string;
  muted: string;
  accent: string;
  border: string;
};

export type ProfileCardOptions = {
  type: ProfileCardType;
  theme: ProfileCardTheme;
  title?: string;
  subtitle?: string;
  showAvatar: boolean;
  showLanguages: boolean;
  width: number;
  height: number;
};

export type ProfileCardData = GitHubStats & {
  avatarDataUri: string;
};


export const PROFILE_CARD_TYPES: ProfileCardType[] = ["repo", "profile", "compact"];

export const PROFILE_THEMES: Record<string, ProfileCardTheme> = {
  github: {
    bg: "#ffffff",
    panel: "#f6f8fa",
    text: "#1f2328",
    muted: "#656d76",
    accent: "#0969da",
    border: "#d0d7de",
  },
  light: {
    bg: "#ffffff",
    panel: "#f8fafc",
    text: "#0f172a",
    muted: "#64748b",
    accent: "#2563eb",
    border: "#cbd5e1",
  },
  dark: {
    bg: "#0d1117",
    panel: "#161b22",
    text: "#f0f6fc",
    muted: "#8b949e",
    accent: "#58a6ff",
    border: "#30363d",
  },
  ocean: {
    bg: "#071a2b",
    panel: "#0b2942",
    text: "#e6f5ff",
    muted: "#9ac7df",
    accent: "#38bdf8",
    border: "#155e75",
  },
  violet: {
    bg: "#18122b",
    panel: "#241b3f",
    text: "#f5f3ff",
    muted: "#c4b5fd",
    accent: "#a78bfa",
    border: "#4c3b78",
  },
  amber: {
    bg: "#21170b",
    panel: "#33230f",
    text: "#fff7df",
    muted: "#e7c98a",
    accent: "#f5b942",
    border: "#6f4d1c",
  },
};


const font = "'Segoe UI',Inter,Ubuntu,-apple-system,BlinkMacSystemFont,sans-serif";

function stat(x: number, y: number, value: string | number, label: string, color: string, muted: string) {
  return `<text x="${x}" y="${y}" font-family="${font}" font-size="30" font-weight="700" fill="${color}">${escapeXml(String(value))}</text><text x="${x}" y="${y + 28}" font-family="${font}" font-size="16" fill="${muted}">${escapeXml(label)}</text>`;
}

function languagePills(data: ProfileCardData, y: number, theme: ProfileCardOptions["theme"]) {
  let x = 70;
  return data.languages.slice(0, 4).map((lang) => {
    const label = `${lang.name} ${lang.percentage}%`;
    const width = Math.max(110, label.length * 9 + 38);
    const out = `<rect x="${x}" y="${y}" width="${width}" height="36" rx="18" fill="${theme.panel}" stroke="${theme.border}"/><circle cx="${x + 19}" cy="${y + 18}" r="5" fill="${lang.color}"/><text x="${x + 32}" y="${y + 23}" font-family="${font}" font-size="14" fill="${theme.text}">${escapeXml(label)}</text>`;
    x += width + 12;
    return out;
  }).join("");
}

function avatar(data: ProfileCardData, x: number, y: number, size: number, theme: ProfileCardOptions["theme"]) {
  if (!data.avatarDataUri) return "";
  const id = `avatar-${x}-${y}`;
  return `<defs><clipPath id="${id}"><rect x="${x}" y="${y}" width="${size}" height="${size}" rx="${Math.round(size * 0.18)}"/></clipPath></defs><rect x="${x - 2}" y="${y - 2}" width="${size + 4}" height="${size + 4}" rx="${Math.round(size * 0.2)}" fill="${theme.border}"/><image href="${data.avatarDataUri}" x="${x}" y="${y}" width="${size}" height="${size}" preserveAspectRatio="xMidYMid slice" clip-path="url(#${id})"/>`;
}

function repoLayout(data: ProfileCardData, options: ProfileCardOptions) {
  const { theme, width, height } = options;
  const heading = escapeXml(options.title || `${data.username}/GitHub profile`);
  const subtitle = escapeXml(options.subtitle || `${data.name || data.username}'s live open-source activity, generated by ghstats.dev.`);
  return `<rect width="${width}" height="${height}" fill="${theme.bg}"/><rect x="1" y="1" width="${width - 2}" height="${height - 2}" rx="28" fill="${theme.bg}" stroke="${theme.border}" stroke-width="2"/>${options.showAvatar ? avatar(data, width - 250, 62, 172, theme) : ""}<text x="70" y="115" font-family="${font}" font-size="34" fill="${theme.text}"><tspan font-weight="400">${escapeXml(data.username)}/</tspan><tspan font-weight="700">GitHub profile</tspan></text><text x="70" y="165" font-family="${font}" font-size="22" fill="${theme.muted}">${heading}</text><text x="70" y="202" font-family="${font}" font-size="18" fill="${theme.muted}">${subtitle}</text>${stat(70, 342, data.followers, "Followers", theme.text, theme.muted)}${stat(250, 342, data.publicRepos, "Public repos", theme.text, theme.muted)}${stat(430, 342, data.totalStars, "Stars earned", theme.text, theme.muted)}${stat(630, 342, data.contributionsThisYear, "Contributions", theme.text, theme.muted)}${stat(870, 342, data.currentStreak, "Day streak", theme.text, theme.muted)}${options.showLanguages ? languagePills(data, 445, theme) : ""}<rect x="0" y="${height - 18}" width="${width}" height="18" fill="${theme.accent}"/><text x="${width - 70}" y="${height - 42}" text-anchor="end" font-family="${font}" font-size="16" fill="${theme.muted}">ghstats.dev/${escapeXml(data.username)}</text>`;
}

function profileLayout(data: ProfileCardData, options: ProfileCardOptions) {
  const { theme, width, height } = options;
  return `<rect width="${width}" height="${height}" fill="${theme.bg}"/><rect x="38" y="38" width="${width - 76}" height="${height - 76}" rx="34" fill="${theme.panel}" stroke="${theme.border}" stroke-width="2"/>${options.showAvatar ? avatar(data, 78, 88, 190, theme) : ""}<text x="305" y="145" font-family="${font}" font-size="46" font-weight="700" fill="${theme.text}">${escapeXml(data.name || data.username)}</text><text x="305" y="190" font-family="${font}" font-size="24" fill="${theme.accent}">@${escapeXml(data.username)}</text><text x="305" y="235" font-family="${font}" font-size="19" fill="${theme.muted}">${escapeXml(options.subtitle || "Building in public on GitHub")}</text>${stat(80, 390, data.contributionsThisYear, "Contributions this year", theme.text, theme.muted)}${stat(365, 390, data.totalStars, "Stars earned", theme.text, theme.muted)}${stat(575, 390, data.totalPRs, "Pull requests", theme.text, theme.muted)}${stat(785, 390, data.followers, "Followers", theme.text, theme.muted)}${options.showLanguages ? languagePills(data, 485, theme) : ""}<text x="${width - 78}" y="${height - 72}" text-anchor="end" font-family="${font}" font-size="16" fill="${theme.muted}">ghstats.dev/${escapeXml(data.username)}</text>`;
}

function compactLayout(data: ProfileCardData, options: ProfileCardOptions) {
  const { theme, width, height } = options;
  return `<rect width="${width}" height="${height}" fill="${theme.bg}"/><rect x="1" y="1" width="${width - 2}" height="${height - 2}" rx="24" fill="${theme.panel}" stroke="${theme.border}" stroke-width="2"/>${options.showAvatar ? avatar(data, 48, 48, 140, theme) : ""}<text x="225" y="93" font-family="${font}" font-size="34" font-weight="700" fill="${theme.text}">${escapeXml(data.name || data.username)}</text><text x="225" y="132" font-family="${font}" font-size="20" fill="${theme.accent}">@${escapeXml(data.username)}</text>${stat(225, 220, data.followers, "Followers", theme.text, theme.muted)}${stat(400, 220, data.totalStars, "Stars", theme.text, theme.muted)}${stat(550, 220, data.publicRepos, "Repos", theme.text, theme.muted)}${stat(700, 220, data.contributionsThisYear, "Contributions", theme.text, theme.muted)}<text x="${width - 46}" y="${height - 35}" text-anchor="end" font-family="${font}" font-size="14" fill="${theme.muted}">ghstats.dev</text>`;
}

export function renderProfileCard(data: ProfileCardData, options: ProfileCardOptions): string {
  const body = options.type === "profile" ? profileLayout(data, options) : options.type === "compact" ? compactLayout(data, options) : repoLayout(data, options);
  return `<svg width="${options.width}" height="${options.height}" viewBox="0 0 ${options.width} ${options.height}" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="${escapeXml(data.username)} GitHub profile card"><title>${escapeXml(data.username)} GitHub profile card</title>${body}</svg>`;
}


export function resolveProfileCardOptions(params: URLSearchParams): ProfileCardOptions {
  const type = PROFILE_CARD_TYPES.includes(params.get("type") as ProfileCardType) ? params.get("type") as ProfileCardType : "repo";
  const preset = PROFILE_THEMES[params.get("theme") || "github"] || PROFILE_THEMES.github;
  const custom = (key: keyof ProfileCardTheme) => sanitizeHexParam(params.get(key)) || preset[key];
  const compact = type === "compact";
  return {
    type,
    theme: { bg: custom("bg"), panel: custom("panel"), text: custom("text"), muted: custom("muted"), accent: custom("accent"), border: custom("border") },
    title: params.get("title")?.slice(0, 80) || undefined,
    subtitle: params.get("subtitle")?.slice(0, 140) || undefined,
    showAvatar: params.get("show_avatar") !== "false",
    showLanguages: !compact && params.get("show_languages") !== "false",
    width: compact ? 1000 : 1200,
    height: compact ? 320 : 627,
  };
}

export type RepositoryCardData = {
  owner: string;
  name: string;
  description: string;
  ownerAvatarUrl: string;
  avatarDataUri: string;
  contributors: number;
  openIssues: number;
  stars: number;
  forks: number;
};

export function parseRepository(value: string | null): { owner: string; repo: string } | null {
  const match = value?.trim().match(/^([A-Za-z0-9](?:[A-Za-z0-9-]{0,38}))\/([A-Za-z0-9._-]{1,100})$/);
  return match ? { owner: match[1], repo: match[2] } : null;
}

export async function fetchRepositoryCardData(owner: string, repo: string): Promise<RepositoryCardData> {
  const token = process.env.GITHUB_TOKEN || process.env.GH_TOKEN || process.env.GITHUB_ACCESS_TOKEN;
  const headers: Record<string, string> = { Accept: "application/vnd.github+json", "User-Agent": "github-profile-stats" };
  if (token) headers.Authorization = `Bearer ${token}`;
  const response = await fetch(`https://api.github.com/repos/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}`, { headers, cache: "no-store" });
  if (!response.ok) throw new Error(response.status === 404 ? `Repository "${owner}/${repo}" not found` : `GitHub API responded with status ${response.status}`);
  const json = await response.json();
  let contributors = 0;
  try {
    const contributorsResponse = await fetch(`${json.contributors_url}?per_page=1&anon=true`, { headers, cache: "no-store" });
    if (contributorsResponse.ok) {
      const link = contributorsResponse.headers.get("link") || "";
      const last = link.match(/[?&]page=(\d+)>; rel="last"/);
      contributors = last ? Number(last[1]) : (await contributorsResponse.json()).length;
    }
  } catch {}
  return { owner: json.owner.login, name: json.name, description: json.description || "A GitHub repository", ownerAvatarUrl: json.owner.avatar_url, avatarDataUri: "", contributors, openIssues: json.open_issues_count, stars: json.stargazers_count, forks: json.forks_count };
}

export function renderRepositoryCard(data: RepositoryCardData, options: ProfileCardOptions): string {
  const { theme, width, height } = options;
  const avatarSvg = options.showAvatar && data.avatarDataUri ? avatar({ username: data.owner, avatarDataUri: data.avatarDataUri } as ProfileCardData, width - 250, 62, 172, theme) : "";
  const body = `<rect width="${width}" height="${height}" fill="${theme.bg}"/><rect x="1" y="1" width="${width - 2}" height="${height - 2}" rx="28" fill="${theme.bg}" stroke="${theme.border}" stroke-width="2"/>${avatarSvg}<text x="70" y="125" font-family="${font}" font-size="38" font-weight="400" fill="${theme.text}">${escapeXml(data.owner)}/</text><text x="${70 + Math.min(data.owner.length * 22 + 22, 360)}" y="125" font-family="${font}" font-size="38" font-weight="700" fill="${theme.text}">${escapeXml(data.name)}</text><text x="70" y="185" font-family="${font}" font-size="22" fill="${theme.muted}">${escapeXml((options.subtitle || data.description).slice(0, 95))}</text>${stat(70, 365, data.contributors, "Contributors", theme.text, theme.muted)}${stat(295, 365, data.openIssues, "Open issues", theme.text, theme.muted)}${stat(505, 365, data.stars, "Stars", theme.text, theme.muted)}${stat(690, 365, data.forks, "Forks", theme.text, theme.muted)}<rect x="0" y="${height - 18}" width="${width}" height="18" fill="${theme.accent}"/><text x="${width - 70}" y="${height - 42}" text-anchor="end" font-family="${font}" font-size="16" fill="${theme.muted}">github.com/${escapeXml(data.owner)}/${escapeXml(data.name)}</text>`;
  return `<svg width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="${escapeXml(data.owner)}/${escapeXml(data.name)} repository card"><title>${escapeXml(data.owner)}/${escapeXml(data.name)} repository card</title>${body}</svg>`;
}
