import { ThemeDefinition } from "../types";

export const THEME_DEFINITIONS: ThemeDefinition[] = [
  {
    key: "default",
    showIn: ["visual_builder", "hero"],
    name: "Default",
    bg: "#0d1117",
    text: "#c9d1d9",
    title: "#58a6ff",
    icon: "#58a6ff",
    border: "#30363d",
  },
  {
    key: "light",
    showIn: ["visual_builder"],
    name: "Light",
    bg: "#ffffff",
    text: "#24292f",
    title: "#0969da",
    icon: "#0969da",
    border: "#d0d7de",
  },
  {
    key: "radical",
    showIn: ["visual_builder", "hero"],
    name: "Radical",
    bg: "#141321",
    text: "#a9fef7",
    title: "#fe428e",
    icon: "#f8d847",
    border: "#fe428e",
  },
  {
    key: "tokyonight",
    showIn: ["visual_builder", "hero"],
    name: "Tokyo Night",
    bg: "#1a1b27",
    text: "#70a5fd",
    title: "#bf91f3",
    icon: "#38bdae",
    border: "#70a5fd",
  },
  {
    key: "dracula",
    showIn: ["visual_builder", "hero"],
    name: "Dracula",
    bg: "#282a36",
    text: "#f8f8f2",
    title: "#ff79c6",
    icon: "#bd93f9",
    border: "#6272a4",
  },
  {
    key: "nord",
    showIn: ["visual_builder"],
    name: "Nord",
    bg: "#2e3440",
    text: "#d8dee9",
    title: "#88c0d0",
    icon: "#88c0d0",
    border: "#4c566a",
  },
  {
    key: "gruvbox",
    showIn: ["visual_builder"],
    name: "Gruvbox",
    bg: "#282828",
    text: "#ebdbb2",
    title: "#fabd2f",
    icon: "#fe8019",
    border: "#3c3836",
  },
  {
    key: "catppuccin",
    showIn: ["visual_builder", "hero"],
    name: "Catppuccin",
    bg: "#1e1e2e",
    text: "#cdd6f4",
    title: "#cba6f7",
    icon: "#f5c2e7",
    border: "#313244",
  },
  {
    key: "ocean",
    showIn: ["visual_builder", "hero"],
    name: "Ocean",
    bg: "#0b1929",
    text: "#a3c4e0",
    title: "#00bfff",
    icon: "#00e5ff",
    border: "#1a3a5c",
  },
  {
    key: "sunset",
    showIn: ["visual_builder", "hero"],
    name: "Sunset",
    bg: "#1a1025",
    text: "#e8d5c4",
    title: "#ff6b6b",
    icon: "#ffa07a",
    border: "#4a2040",
  },
  {
    key: "forest",
    showIn: ["visual_builder", "hero"],
    name: "Forest",
    bg: "#0d1f0d",
    text: "#b5cea8",
    title: "#4ec9b0",
    icon: "#6a9955",
    border: "#1e3a1e",
  },
  {
    key: "midnight",
    showIn: ["visual_builder"],
    name: "Midnight",
    bg: "#020024",
    text: "#eaeaea",
    title: "#00d4ff",
    icon: "#0099ff",
    border: "#090979",
  },
  {
    key: "nightowl",
    showIn: ["visual_builder", "hero"],
    name: "Night Owl",
    bg: "#011627",
    text: "#d6deeb",
    title: "#7fdbca",
    icon: "#c792ea",
    border: "#1d3b53",
  },
  {
    key: "solarized",
    showIn: ["visual_builder", "hero"],
    name: "Solarized",
    bg: "#002b36",
    text: "#839496",
    title: "#2aa198",
    icon: "#b58900",
    border: "#073642",
  },
  {
    key: "ayu",
    showIn: ["visual_builder", "hero"],
    name: "Ayu",
    bg: "#0d1017",
    text: "#bfbdb6",
    title: "#e6b450",
    icon: "#ff8f40",
    border: "#1b1f29",
  },
  {
    key: "rosepine",
    showIn: ["visual_builder", "hero"],
    name: "Rosé Pine",
    bg: "#191724",
    text: "#e0def4",
    title: "#ebbcba",
    icon: "#c4a7e7",
    border: "#26233a",
  },
  {
    key: "kanagawa",
    showIn: ["visual_builder", "hero"],
    name: "Kanagawa",
    bg: "#1F1F28",
    text: "#DCD7BA",
    title: "#7E9CD8",
    icon: "#E6C384",
    border: "#2A2A37",
  },
  {
    key: "palenight",
    showIn: ["visual_builder", "hero"],
    name: "Material Palenight",
    bg: "#292D3E",
    text: "#A6ACCD",
    title: "#82AAFF",
    icon: "#C792EA",
    border: "#2b2a3e",
  },
];
